In [1]:
import numpy as np

****ARRAY OPERATIONS****


Arithmetic operations

In [2]:

a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [21]:
A = np.array([[1,1],[3,4]])
B = np.array([[6,7],[8,10]])
A

array([[1, 1],
       [3, 4]])

In [22]:
B

array([[ 6,  7],
       [ 8, 10]])

In [ ]:
np.dot(A,B) # This is another method of performing the the matrix multiplication

array([[14, 17],
       [50, 61]])

In [23]:
B.T

array([[ 6,  8],
       [ 7, 10]])

Stacking Array

In [24]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [ ]:
np.vstack((a,b))
# One array stacked below another array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((a,b))
# One array stacked horizontally/along with the previous array like->string concatination'+'

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((a,b))
# Stacking arrays along columns

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splitting Array

In [31]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.split(c,2)
# Splits an array into equal-sized subarrays.
# If the split is not possible evenly, it raises an error.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.array_split(c,3)
# This Similar to split(), but allows uneven splits without error.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [38]:
# Split rows into 2 equal parts
rows = np.split(c, 2, axis=0)

# Split columns into 2 equal parts
cols = np.split(c, 2, axis=1)

print("Row split:", rows)
print("Column split:", cols)

Row split: [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
Column split: [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [39]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [40]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

Broadcasting

In [41]:
l = [10,20,30,40]
arr = np.array(l)

In [42]:
arr + 10 


array([20, 30, 40, 50])

In [43]:
arr2 = np.arange(1,26).reshape(5,5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])


Deep and Shallow copy

In [45]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [47]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
a[4:6] *10 


array([50, 60])

In [49]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
a
b = a.copy()

In [51]:
b[0] = 99 
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])