In [1]:
import numpy as np


NUMPY INDEXING AND SLICING OF VECTORS

In [2]:

arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [4]:
arr[4]


15

In [13]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

In [14]:
arr[4]

array([21, 22, 23, 24, 25])

In [6]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [8]:
arr[:,2]
#This gives all rows elements but only of one-column

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [9]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [11]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])